language: minimal
os: linux
services:
  - docker
before_install:
  - docker build -t prashantbist/frontend-dev -f Dockerfile.dev . 
script:
  - docker run -e CI=true prashantbist/frontend-dev npm run test -- --coverage
install: 
  - docker build -t prashantbist/frontend .

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-123456789012"
  bucket_path: "docker-frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"