services:
  redis-server:
    image: redis
    restart: always
    networks:
      - myweb-counter-network
    ports:
      - 6379:6379
  my-counterapp:
    build: .   
    restart: unless-stopped
    networks:
      - myweb-counter-network
    ports:
      - 8000:8000
    depends_on:
      - redis-server
networks:
  myweb-counter-network:
    driver: bridge 

